apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "isolation-forest.fullname" . }}
  labels:
    {{- include "isolation-forest.labels" . | nindent 4 }}
data:
  CONTAMINATION: {{ .Values.config.contamination | quote }}
  MODEL_VERSION: {{ .Values.config.modelVersion | quote }}
  DATA_CSV: {{ .Values.config.dataCsv | quote }}
